name: Deploy via FTPS
on:
  push:
    branches: [main]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupération du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Étape de build (si nécessaire)
      - name: Build (si nécessaire)
        run: |
          

      # 3️⃣ Synchronisation des fichiers via FTPS
      - name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}          
          username: ${{ secrets.FTP_USERNAME }}    
          password: ${{ secrets.FTP_PASSWORD }}    
          protocol: ftps                           # FTPS explicite
          port: 21                                 # Port FTP standard
          local-dir: ./app/                        # chemin relatif dans le repo
          server-dir: ./sites/pentest-lab.jobmakombela.fr/
          exclude: |
            **/.git*
            **/node_modules/*
            **/vendor/*
            **/var/cache/*
            **/var/log/*
          dry-run: false